FROM python:3.9-slim

WORKDIR /app

# Copy Flask app files into the container
COPY ./GlobalRates_web /app

RUN pip install --no-cache-dir -r ./requirements.txt

# Run the Flask app
CMD ["flask", "run", "--host=0.0.0.0"]
